consumes:
- application/json
info:
  title: Swaggerdoc
  version: 0.1.0
paths: {}
produces:
- application/json
schemes:
- http
swagger: "2.0"

definitions:
  user:
    type: object
    required:
      - id
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      username:
        type: string
        minLength: 1
      email:
        type: string
        minLength: 1
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string

paths:
  /:
    get:
      tags:
        - users
      parameters:
        - name: since
          in: query
          type: integer
          format: int64
        - name: limit
          in: query
          type: integer
          format: int32
          default: 20
      responses:
        200:
          description: list all users
          schema: 
            type: array
            items:
              $ref: "#/definitions/user"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"

